// import Image from "next/image";
// import styles from "./page.module.css";
import styles from "./page.module.css";
import dynamic from 'next/dynamic';

const metadata = {
  title: "Home | Next App",
  description: "Generated by create next app",
};

const Slider = dynamic(() => import('./components/Slider/Slider'), { ssr: false });

export default function Home() {
  return (
    <main className={styles.main}>
      <h1>Ресторан <span className={styles.titleFoodSta}>"Food Sta"</span></h1>
      <div className={styles.description}>
        <Slider />
      </div>
    </main>
  );
}

export { metadata };